### PR TITLE
Allow use of MatrixAggregatable as an extension

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/matrix-project-plugin/pull/53.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
@reviewbybees done

**Comment by uhafner** [comment]
I will get back on this after my vacation (end of September).

**Comment by uhafner** [comment]
Integrated in branch 3.0.

**Comment by uhafner** [comment]
Thank

**Pull request closed without merging**
